list(APPEND INCLUDEPATH ${CMAKE_CURRENT_LIST_DIR})

#list(APPEND SOURCES ${CMAKE_CURRENT_LIST_DIR}/test_bytes.cpp)
#list(APPEND SOURCES ${CMAKE_CURRENT_LIST_DIR}/catch_amalgamated.cpp)
list(APPEND SOURCES ${CMAKE_CURRENT_LIST_DIR}/test_str.cpp)
list(APPEND SOURCES ${CMAKE_CURRENT_LIST_DIR}/test_main.cpp)
