//
// Created by luolijun on 2021/10/9.
//
#include "tiny/chars.h"

namespace tiny {

uint16_t chars::mapping[256] = {
    /*  <NUL>           0x00 */ CNTRL,
    /*  <SOH>           0x01 */ CNTRL,
    /*  <STX>           0x02 */ CNTRL,
    /*  <ETX>           0x03 */ CNTRL,
    /*  <EOT>           0x04 */ CNTRL,
    /*  <ENQ>           0x05 */ CNTRL,
    /*  <ACK>           0x06 */ CNTRL,
    /*  <BEL>    '\a'   0x07 */ CNTRL,
    /*  <BS>            0x08 */ CNTRL,
    /*  <HT>     '\t'   0x09 */ CNTRL | SPACE | BLANK,
    /*  <LF>     '\n'   0x0a */ CNTRL | SPACE,
    /*  <VT>     '\v'   0x0b */ CNTRL | SPACE,
    /*  <FF>     '\f'   0x0c */ CNTRL | SPACE,
    /*  <CR>     '\r'   0x0d */ CNTRL | SPACE,
    /*  <SO>            0x0e */ CNTRL | 0,
    /*  <SI>            0x0f */ CNTRL | 0,
    /*  <DLE>           0x10 */ CNTRL | 0,
    /*  <DC1>           0x11 */ CNTRL | 0,
    /*  <DC2>           0x12 */ CNTRL | 0,
    /*  <DC3>           0x13 */ CNTRL | 0,
    /*  <DC4>           0x14 */ CNTRL | 0,
    /*  <NAK>           0x15 */ CNTRL | 0,
    /*  <SYN>           0x16 */ CNTRL | 0,
    /*  <ETB>           0x17 */ CNTRL | 0,
    /*  <CAN>           0x18 */ CNTRL | 0,
    /*  <EM>            0x19 */ CNTRL | 0,
    /*  <SUB>           0x1a */ CNTRL | 0,
    /*  <ESC>           0x1b */ CNTRL | 0,
    /*  <FS>            0x1c */ CNTRL | 0,
    /*  <GS>            0x1d */ CNTRL | 0,
    /*  <RS>            0x1e */ CNTRL | 0,
    /*  <US>            0x1f */ CNTRL | 0,
    /*  <SP>     ' '    0x20 */ PRINT | SPACE | BLANK,
    /*  -----    '!'    0x21 */ PRINT | PUNCT,
    /*  -----    '"'    0x22 */ PRINT | PUNCT,
    /*  -----    '#'    0x23 */ PRINT | PUNCT,
    /*  -----    '$'    0x24 */ PRINT | PUNCT,
    /*  -----    '%'    0x25 */ PRINT | PUNCT,
    /*  -----    '&'    0x26 */ PRINT | PUNCT,
    /*  -----    '''    0x27 */ PRINT | PUNCT,
    /*  -----    '('    0x28 */ PRINT | PUNCT,
    /*  -----    ')'    0x29 */ PRINT | PUNCT,
    /*  -----    '*'    0x2a */ PRINT | PUNCT,
    /*  -----    '+'    0x2b */ PRINT | PUNCT,
    /*  -----    ','    0x2c */ PRINT | PUNCT,
    /*  -----    '-'    0x2d */ PRINT | PUNCT,
    /*  -----    '.'    0x2e */ PRINT | PUNCT,
    /*  -----    '/'    0x2f */ PRINT | PUNCT,
    /*  -----    '0'    0x30 */ PRINT | DIGIT | HEX | DEC | OCT | BIN,
    /*  -----    '1'    0x31 */ PRINT | DIGIT | HEX | DEC | OCT | BIN,
    /*  -----    '2'    0x32 */ PRINT | DIGIT | HEX | DEC | OCT,
    /*  -----    '3'    0x33 */ PRINT | DIGIT | HEX | DEC | OCT,
    /*  -----    '4'    0x34 */ PRINT | DIGIT | HEX | DEC | OCT,
    /*  -----    '5'    0x35 */ PRINT | DIGIT | HEX | DEC | OCT,
    /*  -----    '6'    0x36 */ PRINT | DIGIT | HEX | DEC | OCT,
    /*  -----    '7'    0x37 */ PRINT | DIGIT | HEX | DEC | OCT,
    /*  -----    '8'    0x38 */ PRINT | DIGIT | HEX | DEC,
    /*  -----    '9'    0x39 */ PRINT | DIGIT | HEX | DEC,
    /*  -----    ':'    0x3a */ PRINT | PUNCT,
    /*  -----    ';'    0x3b */ PRINT | PUNCT,
    /*  -----    '<'    0x3c */ PRINT | PUNCT,
    /*  -----    '='    0x3d */ PRINT | PUNCT,
    /*  -----    '>'    0x3e */ PRINT | PUNCT,
    /*  -----    '?'    0x3f */ PRINT | PUNCT,
    /*  -----    '@'    0x40 */ PRINT | PUNCT,
    /*  -----    'A'    0x41 */ PRINT | UPPER | HEX,
    /*  -----    'B'    0x42 */ PRINT | UPPER | HEX,
    /*  -----    'C'    0x43 */ PRINT | UPPER | HEX,
    /*  -----    'D'    0x44 */ PRINT | UPPER | HEX,
    /*  -----    'E'    0x45 */ PRINT | UPPER | HEX,
    /*  -----    'F'    0x46 */ PRINT | UPPER | HEX,
    /*  -----    'G'    0x47 */ PRINT | UPPER,
    /*  -----    'H'    0x48 */ PRINT | UPPER,
    /*  -----    'I'    0x49 */ PRINT | UPPER,
    /*  -----    'J'    0x4a */ PRINT | UPPER,
    /*  -----    'K'    0x4b */ PRINT | UPPER,
    /*  -----    'L'    0x4c */ PRINT | UPPER,
    /*  -----    'M'    0x4d */ PRINT | UPPER,
    /*  -----    'N'    0x4e */ PRINT | UPPER,
    /*  -----    'O'    0x4f */ PRINT | UPPER,
    /*  -----    'P'    0x50 */ PRINT | UPPER,
    /*  -----    'Q'    0x51 */ PRINT | UPPER,
    /*  -----    'R'    0x52 */ PRINT | UPPER,
    /*  -----    'S'    0x53 */ PRINT | UPPER,
    /*  -----    'T'    0x54 */ PRINT | UPPER,
    /*  -----    'U'    0x55 */ PRINT | UPPER,
    /*  -----    'V'    0x56 */ PRINT | UPPER,
    /*  -----    'W'    0x57 */ PRINT | UPPER,
    /*  -----    'X'    0x58 */ PRINT | UPPER,
    /*  -----    'Y'    0x59 */ PRINT | UPPER,
    /*  -----    'Z'    0x5a */ PRINT | UPPER,
    /*  -----    '['    0x5b */ PRINT | PUNCT,
    /*  -----    '\'    0x5c */ PRINT | PUNCT,
    /*  -----    ']'    0x5d */ PRINT | PUNCT,
    /*  -----    '^'    0x5e */ PRINT | PUNCT,
    /*  -----    '_'    0x5f */ PRINT | PUNCT,
    /*  -----    '`'    0x60 */ PRINT | PUNCT,
    /*  -----    'a'    0x61 */ PRINT | LOWER | HEX,
    /*  -----    'b'    0x62 */ PRINT | LOWER | HEX,
    /*  -----    'c'    0x63 */ PRINT | LOWER | HEX,
    /*  -----    'd'    0x64 */ PRINT | LOWER | HEX,
    /*  -----    'e'    0x65 */ PRINT | LOWER | HEX,
    /*  -----    'f'    0x66 */ PRINT | LOWER | HEX,
    /*  -----    'g'    0x67 */ PRINT | LOWER,
    /*  -----    'h'    0x68 */ PRINT | LOWER,
    /*  -----    'i'    0x69 */ PRINT | LOWER,
    /*  -----    'j'    0x6a */ PRINT | LOWER,
    /*  -----    'k'    0x6b */ PRINT | LOWER,
    /*  -----    'l'    0x6c */ PRINT | LOWER,
    /*  -----    'm'    0x6d */ PRINT | LOWER,
    /*  -----    'n'    0x6e */ PRINT | LOWER,
    /*  -----    'o'    0x6f */ PRINT | LOWER,
    /*  -----    'p'    0x70 */ PRINT | LOWER,
    /*  -----    'q'    0x71 */ PRINT | LOWER,
    /*  -----    'r'    0x72 */ PRINT | LOWER,
    /*  -----    's'    0x73 */ PRINT | LOWER,
    /*  -----    't'    0x74 */ PRINT | LOWER,
    /*  -----    'u'    0x75 */ PRINT | LOWER,
    /*  -----    'v'    0x76 */ PRINT | LOWER,
    /*  -----    'w'    0x77 */ PRINT | LOWER,
    /*  -----    'x'    0x78 */ PRINT | LOWER,
    /*  -----    'y'    0x79 */ PRINT | LOWER,
    /*  -----    'z'    0x7a */ PRINT | LOWER,
    /*  -----    '{'    0x7b */ PRINT | PUNCT,
    /*  -----    '|'    0x7c */ PRINT | PUNCT,
    /*  -----    '}'    0x7d */ PRINT | PUNCT,
    /*  -----    '~'    0x7e */ PRINT | PUNCT,
    /*  <DEL>    ---    0x7f */ CNTRL,
};

} // namespace tiny