list(APPEND INCLUDEPATH ${CMAKE_CURRENT_LIST_DIR})

#list(APPEND SOURCES ${CMAKE_CURRENT_LIST_DIR}/charset.cpp)
#list(APPEND SOURCES ${CMAKE_CURRENT_LIST_DIR}/bytes.cpp)
#list(APPEND SOURCES ${CMAKE_CURRENT_LIST_DIR}/core.cpp)
list(APPEND SOURCES ${CMAKE_CURRENT_LIST_DIR}/str.cpp)
#list(APPEND SOURCES ${CMAKE_CURRENT_LIST_DIR}/view.cpp)
