list(APPEND INCLUDEPATH ${CMAKE_CURRENT_LIST_DIR})

list(APPEND SOURCES ${CMAKE_CURRENT_LIST_DIR}/re.cpp)
list(APPEND SOURCES ${CMAKE_CURRENT_LIST_DIR}/str.cpp)
list(APPEND SOURCES ${CMAKE_CURRENT_LIST_DIR}/escape.cpp)
list(APPEND SOURCES ${CMAKE_CURRENT_LIST_DIR}/unescape.cpp)
